# Generated by Django 5.0.2 on 2024-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_medicine_manufacturer_medicine_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='details',
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pack_size_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='short_composition1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='short_composition2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
